In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =sns.load_dataset('iris')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X= df.drop('species',axis=1)
y=df['species']

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn=KNeighborsClassifier(n_neighbors=5)

In [10]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
model_knn.score(X_test,y_test)

1.0

In [12]:
from sklearn.svm import SVC
model_svm=SVC(gamma='auto')

In [13]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [14]:
model_svm.score(X_test,y_test)

1.0

In [15]:
# now let use grid sreach cv

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [18]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [19]:
classifier.cv_results_

{'mean_fit_time': array([0.00879769, 0.00487399, 0.00449495, 0.00496116, 0.00370183,
        0.00349913, 0.00607338, 0.01136708]),
 'std_fit_time': array([0.00340361, 0.00216511, 0.00170444, 0.0026081 , 0.00034062,
        0.00047915, 0.00336737, 0.00528022]),
 'mean_score_time': array([0.00671554, 0.00302367, 0.00378499, 0.00348263, 0.00303593,
        0.00383825, 0.00406055, 0.00583334]),
 'std_score_time': array([0.00268932, 0.00049286, 0.00134289, 0.00163523, 0.00083515,
        0.00214557, 0.00184083, 0.00178145]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [20]:
results = pd.DataFrame(classifier.cv_results_)

In [21]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008798,0.003404,0.006716,0.002689,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004874,0.002165,0.003024,0.000493,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004495,0.001704,0.003785,0.001343,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004961,0.002608,0.003483,0.001635,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003702,0.000341,0.003036,0.000835,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003499,0.000479,0.003838,0.002146,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.006073,0.003367,0.004061,0.001841,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.011367,0.005280,0.005833,0.001781,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [22]:
classifier1 = GridSearchCV((model_knn),{
    'n_neighbors':[5,10,15,20],
    'weights':['uniform','distance'],
    'algorithm':['auto','ball_tree','kd_tree','brute'],
    'leaf_size':[10,20,30,40],
    'p':[1,2]

    },cv=5,return_train_score=False)

In [23]:
classifier1.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 20, 30, 40],
                         'n_neighbors': [5, 10, 15, 20], 'p': [1, 2],
                         'weights': ['uniform', 'distance']})

In [24]:
results1 = pd.DataFrame(classifier1.cv_results_)

In [25]:
results1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003858,0.001548,0.005836,0.001807,auto,10,5,1,uniform,"{'algorithm': 'auto', 'leaf_size': 10, 'n_neig...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,209
1,0.002018,0.000090,0.002454,0.000216,auto,10,5,1,distance,"{'algorithm': 'auto', 'leaf_size': 10, 'n_neig...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,209
2,0.001968,0.000047,0.002851,0.000092,auto,10,5,2,uniform,"{'algorithm': 'auto', 'leaf_size': 10, 'n_neig...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,33
3,0.001955,0.000038,0.002353,0.000118,auto,10,5,2,distance,"{'algorithm': 'auto', 'leaf_size': 10, 'n_neig...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,171
4,0.001952,0.000015,0.002899,0.000054,auto,10,10,1,uniform,"{'algorithm': 'auto', 'leaf_size': 10, 'n_neig...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,0.001715,0.000030,0.002121,0.000025,brute,40,15,2,distance,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,33
252,0.001869,0.000310,0.002959,0.000233,brute,40,20,1,uniform,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,33
253,0.001716,0.000029,0.002078,0.000068,brute,40,20,1,distance,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,33
254,0.001782,0.000084,0.002937,0.000028,brute,40,20,2,uniform,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.933333,1.000000,0.933333,0.933333,1.0,0.960000,0.032660,241
255,0.001694,0.000040,0.002161,0.000041,brute,40,20,2,distance,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,33

In [26]:
from sklearn.model_selection import RandomizedSearchCV

In [27]:
classifier2 = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=4)

In [28]:
classifier2.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [29]:
resluts =pd.DataFrame(classifier2.cv_results_)

In [30]:
resluts

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003967,0.000950,0.002589,0.000263,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
1,0.003132,0.000044,0.002329,0.000033,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002914,0.000082,0.002286,0.000008,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003066,0.000143,0.002425,0.000148,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3